### ISSUE TITLE
Support multichoice items in properties

### ISSUE THREAD

**Issue by deSagaz** [TheFeedFactory/ndtrc_model#1]
The front-end is currently sending the following to the back-end for multichoice properties:

<img width="185" alt="image" src="https://user-images.githubusercontent.com/4922048/162172425-1db366b9-6a7d-4d6f-a978-f5efc254acde.png">

The check at the back-end expects a valueid, but should check for items in the categoryvalues array (I am presuming):

https://github.com/TheFeedFactory/ndtrc_model/blob/cd9ed01a5601b7009627fbbd83028e92c58f11b3/src/main/groovy/nl/ithelden/model/ndtrc/TRCItemCategories.groovy#L64

https://github.com/TheFeedFactory/ndtrc_model/blob/3a38dbc7e4749c9805a23e6d7d863e20c9437290/src/main/groovy/nl/ithelden/model/ndtrc/SubItemGroup.groovy#L35

**Comment by mjumelet** [comment]
@deSagaz Good find, I think you are corrected, corrected it and deployed it.
